use_frameworks!

platform :ios, '9.0'

target 'CommonLibHelperCapstone_Example' do
  pod 'CommonLibHelperCapstone', :path => '../'

  target 'CommonLibHelperCapstone_Tests' do
    inherit! :search_paths

    
  end
end
